package runtime

import "sort"

func defaultExportProfileCatalog() []ExportProfileCatalogEntry {
	entries := []ExportProfileCatalogEntry{
		{
			ExportProfile:           "operator_review",
			Label:                   "Operator Review",
			Description:             "Governed review output for operator-facing Chat, VS Code, and CLI surfaces.",
			ReportTypes:             []string{"review", "report"},
			DefaultAudience:         "operator",
			AllowedAudiences:        []string{"operator", "security_review", "exec_review"},
			DefaultRetentionClass:   "standard",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "archive",
				"exec_review":     "archive",
			},
			ClientSurfaces:   []string{"chat", "vscode", "cli"},
			DeliveryChannels: []string{"copy", "download", "report"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "operator_follow",
			Label:                   "Operator Follow",
			Description:             "Lower-noise governed follow output for operator-facing live thread and session review.",
			ReportTypes:             []string{"delta-report", "follow"},
			DefaultAudience:         "operator",
			AllowedAudiences:        []string{"operator", "security_review"},
			DefaultRetentionClass:   "short",
			AllowedRetentionClasses: []string{"short", "standard"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "standard",
			},
			ClientSurfaces:   []string{"chat", "vscode", "cli"},
			DeliveryChannels: []string{"stream", "report"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "workflow_review",
			Label:                   "Workflow Review",
			Description:             "Governed workflow and ticket review output for downstream operators.",
			ReportTypes:             []string{"report", "review"},
			DefaultAudience:         "workflow_operator",
			AllowedAudiences:        []string{"workflow_operator", "security_review", "ticket_reviewer"},
			DefaultRetentionClass:   "standard",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "archive",
			},
			ClientSurfaces:   []string{"workflow"},
			DeliveryChannels: []string{"comment", "update", "report"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "workflow_follow",
			Label:                   "Workflow Follow",
			Description:             "Governed low-noise workflow updates for existing tickets and work items.",
			ReportTypes:             []string{"delta-report", "follow"},
			DefaultAudience:         "workflow_operator",
			AllowedAudiences:        []string{"workflow_operator", "ticket_reviewer"},
			DefaultRetentionClass:   "short",
			AllowedRetentionClasses: []string{"short", "standard"},
			AudienceRetentionClassOverlays: map[string]string{
				"ticket_reviewer": "standard",
			},
			ClientSurfaces:   []string{"workflow"},
			DeliveryChannels: []string{"update", "comment", "stream"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "conversation_review",
			Label:                   "Conversation Review",
			Description:             "Governed review output for ChatOps conversations and threaded operator follow-up.",
			ReportTypes:             []string{"report", "review"},
			DefaultAudience:         "conversation_operator",
			AllowedAudiences:        []string{"conversation_operator", "security_review", "channel_reviewer"},
			DefaultRetentionClass:   "standard",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "archive",
			},
			ClientSurfaces:   []string{"chatops"},
			DeliveryChannels: []string{"update", "thread_reply", "report"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "conversation_follow",
			Label:                   "Conversation Follow",
			Description:             "Governed low-noise follow output for existing external conversation threads.",
			ReportTypes:             []string{"delta-report", "follow"},
			DefaultAudience:         "conversation_operator",
			AllowedAudiences:        []string{"conversation_operator", "channel_reviewer"},
			DefaultRetentionClass:   "short",
			AllowedRetentionClasses: []string{"short", "standard"},
			AudienceRetentionClassOverlays: map[string]string{
				"channel_reviewer": "standard",
			},
			ClientSurfaces:   []string{"chatops"},
			DeliveryChannels: []string{"update", "thread_reply", "stream"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "audit_export",
			Label:                   "Audit Export",
			Description:             "Governed audit export for downstream review and evidence sharing.",
			ReportTypes:             []string{"export", "handoff"},
			DefaultAudience:         "downstream_review",
			AllowedAudiences:        []string{"downstream_review", "security_review", "compliance_review"},
			DefaultRetentionClass:   "archive",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"downstream_review": "standard",
				"security_review":   "archive",
				"compliance_review": "archive",
			},
			ClientSurfaces:   []string{"desktop", "runtime"},
			DeliveryChannels: []string{"download", "copy", "preview"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "audit_handoff",
			Label:                   "Audit Handoff",
			Description:             "Governed audit handoff summary for downstream evidence review.",
			ReportTypes:             []string{"handoff"},
			DefaultAudience:         "downstream_review",
			AllowedAudiences:        []string{"downstream_review", "security_review"},
			DefaultRetentionClass:   "short",
			AllowedRetentionClasses: []string{"short", "standard"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "standard",
			},
			ClientSurfaces:   []string{"desktop"},
			DeliveryChannels: []string{"copy", "preview"},
			RedactionMode:    "text",
		},
		{
			ExportProfile:           "evidence_export",
			Label:                   "Evidence Export",
			Description:             "Governed session evidence export for downstream review and evidence retention workflows.",
			ReportTypes:             []string{"export"},
			DefaultAudience:         "downstream_review",
			AllowedAudiences:        []string{"downstream_review", "security_review", "compliance_review"},
			DefaultRetentionClass:   "archive",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"downstream_review": "standard",
				"security_review":   "archive",
				"compliance_review": "archive",
			},
			ClientSurfaces:   []string{"runtime"},
			DeliveryChannels: []string{"download", "copy"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "incident_export",
			Label:                   "Incident Export",
			Description:             "Governed incident package export for security response and downstream filing.",
			ReportTypes:             []string{"export", "handoff"},
			DefaultAudience:         "incident_response",
			AllowedAudiences:        []string{"incident_response", "security_review", "executive_incident_review"},
			DefaultRetentionClass:   "archive",
			AllowedRetentionClasses: []string{"standard", "archive"},
			AudienceRetentionClassOverlays: map[string]string{
				"incident_response":         "standard",
				"security_review":           "archive",
				"executive_incident_review": "archive",
			},
			ClientSurfaces:   []string{"desktop"},
			DeliveryChannels: []string{"download", "copy", "preview"},
			RedactionMode:    "structured_and_text",
		},
		{
			ExportProfile:           "incident_handoff",
			Label:                   "Incident Handoff",
			Description:             "Governed incident handoff summary for downstream response coordination.",
			ReportTypes:             []string{"handoff"},
			DefaultAudience:         "incident_response",
			AllowedAudiences:        []string{"incident_response", "security_review"},
			DefaultRetentionClass:   "standard",
			AllowedRetentionClasses: []string{"short", "standard"},
			AudienceRetentionClassOverlays: map[string]string{
				"security_review": "standard",
			},
			ClientSurfaces:   []string{"desktop"},
			DeliveryChannels: []string{"copy", "preview"},
			RedactionMode:    "text",
		},
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ExportProfile < entries[j].ExportProfile
	})
	return entries
}
