package runtime

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

func invokeSessionToolActionID(sessionID, toolType, requestID string) string {
	id := fmt.Sprintf("%s-tool-%s", sessionID, sanitizeIDFragment(toolType))
	if fragment := sanitizeIDFragment(requestID); fragment != "" && fragment != "unknown" {
		return id + "-" + fragment
	}
	return id
}

func parseRawJSONObject(raw json.RawMessage) JSONObject {
	if len(strings.TrimSpace(string(raw))) == 0 {
		return JSONObject{}
	}
	return parseSessionEventPayloadObject(raw)
}

func taskUsesAutogeneratedIntent(task *TaskRecord) bool {
	if task == nil {
		return false
	}
	annotations := parseRawJSONObject(task.Annotations)
	threadIntent := extractJSONObjectValue(annotations["threadIntent"])
	if normalizedInterfaceBool(threadIntent["autogenerated"]) {
		return true
	}
	return strings.EqualFold(strings.TrimSpace(normalizedInterfaceString(threadIntent["source"])), "autogenerated")
}

func taskIntentForWorkerContext(task *TaskRecord) string {
	if task == nil || taskUsesAutogeneratedIntent(task) {
		return ""
	}
	return strings.TrimSpace(task.Intent)
}

func normalizedInterfaceInt(value interface{}, fallback int) int {
	switch typed := value.(type) {
	case nil:
		return fallback
	case int:
		if typed > 0 {
			return typed
		}
	case int64:
		if typed > 0 {
			return int(typed)
		}
	case float64:
		if typed > 0 {
			return int(typed)
		}
	case json.Number:
		if parsed, err := typed.Int64(); err == nil && parsed > 0 {
			return int(parsed)
		}
	case string:
		if parsed, err := json.Number(strings.TrimSpace(typed)).Int64(); err == nil && parsed > 0 {
			return int(parsed)
		}
	}
	return fallback
}

func copyJSONObject(value JSONObject) JSONObject {
	if len(value) == 0 {
		return JSONObject{}
	}
	clone := make(JSONObject, len(value))
	for key, item := range value {
		clone[key] = item
	}
	return clone
}

type managedWorkerResumeContext struct {
	task                *TaskRecord
	worker              *SessionWorkerRecord
	profile             agentProfileConfig
	systemPrompt        string
	maxOutputTokens     int
	previousOutputText  string
	previousRawResponse json.RawMessage
}

type managedWorkerResumePlan struct {
	requestPayloadFields map[string]interface{}
	sessionEventSummary  string
	progressSummary      string
	progressStage        string
	progressPercent      int
	commandText          string
	commandCWD           string
	timeoutSeconds       int
	executionResult      *TerminalExecutionResult
	executionError       string
	governedRun          *RunRecord
	failureRawResponse   json.RawMessage
}

func (s *APIServer) findSessionToolActionByID(ctx context.Context, sessionID, toolActionID string) (*ToolActionRecord, error) {
	if s == nil || s.store == nil || strings.TrimSpace(sessionID) == "" || strings.TrimSpace(toolActionID) == "" {
		return nil, nil
	}
	items, err := s.store.ListToolActions(ctx, ToolActionListQuery{
		SessionID: sessionID,
		Limit:     1000,
	})
	if err != nil {
		return nil, err
	}
	for i := range items {
		if items[i].ToolActionID == toolActionID {
			item := items[i]
			return &item, nil
		}
	}
	return nil, nil
}

func (s *APIServer) findLatestManagedTurnToolAction(ctx context.Context, sessionID string) (*ToolActionRecord, error) {
	if s == nil || s.store == nil || strings.TrimSpace(sessionID) == "" {
		return nil, nil
	}
	items, err := s.store.ListToolActions(ctx, ToolActionListQuery{
		SessionID: sessionID,
		Limit:     1000,
	})
	if err != nil {
		return nil, err
	}
	var latest *ToolActionRecord
	for i := range items {
		if !strings.EqualFold(strings.TrimSpace(items[i].ToolType), "managed_agent_turn") {
			continue
		}
		item := items[i]
		if latest == nil || item.UpdatedAt.After(latest.UpdatedAt) || item.CreatedAt.After(latest.CreatedAt) {
			latest = &item
		}
	}
	return latest, nil
}

func (s *APIServer) selectedManagedCodexWorkerForSession(ctx context.Context, session *SessionRecord, workerID string) (*SessionWorkerRecord, error) {
	if s == nil || s.store == nil || session == nil {
		return nil, nil
	}
	items, err := s.store.ListSessionWorkers(ctx, SessionWorkerListQuery{
		SessionID: session.SessionID,
		TenantID:  session.TenantID,
		ProjectID: session.ProjectID,
		Limit:     100,
	})
	if err != nil {
		return nil, err
	}
	candidates := []string{strings.TrimSpace(workerID), strings.TrimSpace(session.SelectedWorkerID)}
	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		for i := range items {
			item := items[i]
			if item.WorkerID != candidate {
				continue
			}
			if strings.EqualFold(strings.TrimSpace(item.WorkerType), "managed_agent") && strings.EqualFold(strings.TrimSpace(item.AdapterID), "codex") {
				return &item, nil
			}
		}
	}
	for i := range items {
		item := items[i]
		if strings.EqualFold(strings.TrimSpace(item.WorkerType), "managed_agent") && strings.EqualFold(strings.TrimSpace(item.AdapterID), "codex") {
			return &item, nil
		}
	}
	return nil, nil
}

func (s *APIServer) prepareManagedWorkerResumeContext(ctx context.Context, session *SessionRecord, proposal *sessionToolProposal, action *ToolActionRecord) (*managedWorkerResumeContext, error) {
	if s == nil || s.store == nil || s.agentInvoker == nil || session == nil || action == nil {
		return nil, fmt.Errorf("managed worker continuation is not configured")
	}
	task, err := s.store.GetTask(ctx, session.TaskID)
	if err != nil || task == nil {
		return nil, fmt.Errorf("managed worker task is unavailable")
	}
	worker, err := s.selectedManagedCodexWorkerForSession(ctx, session, normalizeStringOrDefault(action.WorkerID, proposal.WorkerID))
	if err != nil || worker == nil {
		return nil, fmt.Errorf("managed worker is unavailable")
	}
	settings, err := s.agentInvoker.loadAgentIntegrationSettings(ctx, session.TenantID, session.ProjectID)
	if err != nil {
		return nil, err
	}
	profileID := normalizeStringOrDefault(worker.AgentProfileID, "codex")
	profile, err := settings.resolveProfile(profileID)
	if err != nil {
		return nil, err
	}

	taskAnnotations := parseRawJSONObject(task.Annotations)
	sessionSummary := parseRawJSONObject(session.Summary)
	systemPrompt := normalizedInterfaceString(taskAnnotations["systemPrompt"])
	maxOutputTokens := normalizedInterfaceInt(sessionSummary["maxOutputTokens"], 1024)
	previousTurn, err := s.findLatestManagedTurnToolAction(ctx, session.SessionID)
	if err != nil {
		return nil, err
	}

	return &managedWorkerResumeContext{
		task:            task,
		worker:          worker,
		profile:         profile,
		systemPrompt:    systemPrompt,
		maxOutputTokens: maxOutputTokens,
		previousOutputText: readStringFromJSONRaw(func() json.RawMessage {
			if previousTurn == nil {
				return nil
			}
			return previousTurn.ResultPayload
		}(), "outputText"),
		previousRawResponse: func() json.RawMessage {
			if previousTurn == nil {
				return nil
			}
			return readRawResponseFromJSONRaw(previousTurn.ResultPayload)
		}(),
	}, nil
}

func (s *APIServer) continueManagedWorkerWithPlan(ctx context.Context, session *SessionRecord, proposal *sessionToolProposal, action *ToolActionRecord, prepared *managedWorkerResumeContext, plan managedWorkerResumePlan) bool {
	if s == nil || s.store == nil || s.agentInvoker == nil || session == nil || action == nil || prepared == nil || prepared.task == nil || prepared.worker == nil {
		return false
	}
	now := time.Now().UTC()
	continuationRequestID := fmt.Sprintf("resume-%s-%d", sanitizeIDFragment(normalizeStringOrDefault(proposal.ProposalID, action.ToolActionID)), now.UnixNano())
	continuationToolActionID := invokeSessionToolActionID(session.SessionID, "managed_agent_turn", continuationRequestID)

	requestPayload := map[string]interface{}{
		"requestId":               continuationRequestID,
		"agentProfileId":          prepared.profile.ID,
		"executionMode":           AgentInvokeExecutionModeManagedCodexWorker,
		"continuation":            true,
		"resumeAfterProposalId":   normalizeStringOrDefault(proposal.ProposalID, ""),
		"resumeAfterToolActionId": action.ToolActionID,
	}
	for key, value := range plan.requestPayloadFields {
		requestPayload[key] = value
	}
	s.upsertToolActionBestEffort(ctx, &ToolActionRecord{
		ToolActionID:   continuationToolActionID,
		SessionID:      session.SessionID,
		WorkerID:       prepared.worker.WorkerID,
		TenantID:       session.TenantID,
		ProjectID:      session.ProjectID,
		ToolType:       "managed_agent_turn",
		Status:         ToolActionStatusRequested,
		Source:         "v1alpha2.runtime.workers.codex_bridge.resume",
		RequestPayload: mustMarshalJSON(requestPayload),
		CreatedAt:      now,
		UpdatedAt:      now,
	})
	s.appendSessionEventBestEffort(ctx, &SessionEventRecord{
		SessionID: session.SessionID,
		EventType: SessionEventType("tool_action.requested"),
		Payload: mustMarshalJSON(map[string]interface{}{
			"toolActionId":  continuationToolActionID,
			"toolType":      "managed_agent_turn",
			"workerId":      prepared.worker.WorkerID,
			"requestId":     continuationRequestID,
			"executionMode": AgentInvokeExecutionModeManagedCodexWorker,
			"proposalId":    normalizeStringOrDefault(proposal.ProposalID, ""),
			"summary":       plan.sessionEventSummary,
		}),
		Timestamp: now,
	})

	previousSessionStatus := session.Status
	session.Status = SessionStatusRunning
	session.CompletedAt = nil
	session.UpdatedAt = now
	prepared.task.Status = TaskStatusInProgress
	prepared.task.UpdatedAt = now
	_ = s.store.UpsertTask(ctx, prepared.task)
	_ = s.store.UpsertSession(ctx, session)
	if previousSessionStatus != session.Status {
		s.appendSessionEventBestEffort(ctx, &SessionEventRecord{
			SessionID: session.SessionID,
			EventType: SessionEventType("session.status.changed"),
			Payload: mustMarshalJSON(map[string]interface{}{
				"previousStatus": previousSessionStatus,
				"status":         session.Status,
				"proposalId":     normalizeStringOrDefault(proposal.ProposalID, ""),
				"toolActionId":   continuationToolActionID,
			}),
			Timestamp: now,
		})
	}
	s.upsertSessionWorkerBestEffort(ctx, &SessionWorkerRecord{
		WorkerID:          prepared.worker.WorkerID,
		SessionID:         prepared.worker.SessionID,
		TaskID:            prepared.worker.TaskID,
		TenantID:          prepared.worker.TenantID,
		ProjectID:         prepared.worker.ProjectID,
		WorkerType:        prepared.worker.WorkerType,
		AdapterID:         prepared.worker.AdapterID,
		Status:            WorkerStatusRunning,
		Source:            prepared.worker.Source,
		Capabilities:      append([]string(nil), prepared.worker.Capabilities...),
		Routing:           prepared.worker.Routing,
		AgentProfileID:    prepared.worker.AgentProfileID,
		Provider:          prepared.worker.Provider,
		Transport:         prepared.worker.Transport,
		Model:             prepared.worker.Model,
		TargetEnvironment: prepared.worker.TargetEnvironment,
		Annotations:       prepared.worker.Annotations,
		CreatedAt:         prepared.worker.CreatedAt,
		UpdatedAt:         now,
	})
	progressPayload := map[string]interface{}{
		"stage":        plan.progressStage,
		"percent":      plan.progressPercent,
		"toolActionId": continuationToolActionID,
		"proposalId":   normalizeStringOrDefault(proposal.ProposalID, ""),
	}
	if plan.governedRun != nil {
		progressPayload["runId"] = plan.governedRun.RunID
	}
	s.appendSessionEventBestEffort(ctx, &SessionEventRecord{
		SessionID: session.SessionID,
		EventType: SessionEventType("worker.progress"),
		Payload: mustMarshalJSON(map[string]interface{}{
			"workerId": prepared.worker.WorkerID,
			"status":   WorkerStatusRunning,
			"summary":  plan.progressSummary,
			"payload":  progressPayload,
		}),
		Timestamp: now,
	})

	response, err := s.agentInvoker.ContinueManagedWorkerTurn(ctx, managedWorkerContinuationRequest{
		Meta:                ObjectMeta{TenantID: session.TenantID, ProjectID: session.ProjectID, RequestID: continuationRequestID},
		Profile:             prepared.profile,
		Task:                prepared.task,
		Session:             session,
		Worker:              prepared.worker,
		Proposal:            proposal,
		ToolAction:          action,
		CommandText:         plan.commandText,
		CommandCWD:          plan.commandCWD,
		TimeoutSeconds:      plan.timeoutSeconds,
		ExecutionResult:     plan.executionResult,
		ExecutionError:      plan.executionError,
		GovernedRun:         plan.governedRun,
		SystemPrompt:        prepared.systemPrompt,
		MaxOutputTokens:     prepared.maxOutputTokens,
		PreviousOutputText:  prepared.previousOutputText,
		PreviousRawResponse: prepared.previousRawResponse,
	})
	if err != nil {
		s.markInvokeSessionResult(ctx, prepared.task, session, &AgentInvokeResponse{
			RequestID:        continuationRequestID,
			TaskID:           prepared.task.TaskID,
			SessionID:        session.SessionID,
			SelectedWorkerID: prepared.worker.WorkerID,
			TenantID:         session.TenantID,
			ProjectID:        session.ProjectID,
			AgentProfileID:   prepared.profile.ID,
			ExecutionMode:    AgentInvokeExecutionModeManagedCodexWorker,
			WorkerType:       prepared.worker.WorkerType,
			WorkerAdapterID:  prepared.worker.AdapterID,
			Provider:         prepared.profile.Provider,
			Transport:        prepared.profile.Transport,
			Model:            prepared.profile.Model,
			Route:            "managed_worker_process",
			RawResponse:      append(json.RawMessage(nil), plan.failureRawResponse...),
		}, err, time.Now().UTC())
		return true
	}
	response.TaskID = prepared.task.TaskID
	response.SessionID = session.SessionID
	response.SelectedWorkerID = prepared.worker.WorkerID
	response.ExecutionMode = AgentInvokeExecutionModeManagedCodexWorker
	response.WorkerType = prepared.worker.WorkerType
	response.WorkerAdapterID = prepared.worker.AdapterID
	s.markInvokeSessionResult(ctx, prepared.task, session, response, nil, time.Now().UTC())
	return true
}

func (s *APIServer) continueManagedWorkerAfterToolAction(ctx context.Context, session *SessionRecord, proposal *sessionToolProposal, action *ToolActionRecord, commandText, cwd string, timeoutSeconds int, execResult *TerminalExecutionResult, execErr error, decidedAt time.Time) bool {
	_ = decidedAt
	prepared, err := s.prepareManagedWorkerResumeContext(ctx, session, proposal, action)
	if err != nil {
		return false
	}
	return s.continueManagedWorkerWithPlan(ctx, session, proposal, action, prepared, managedWorkerResumePlan{
		requestPayloadFields: map[string]interface{}{
			"command":        commandText,
			"cwd":            cwd,
			"timeoutSeconds": timeoutSeconds,
			"toolExecution": map[string]interface{}{
				"status": action.Status,
				"exitCode": func() int {
					if execResult != nil {
						return execResult.ExitCode
					}
					return -1
				}(),
				"timedOut": execResult != nil && execResult.TimedOut,
				"outputSha256": func() string {
					if execResult != nil {
						return execResult.OutputSHA256
					}
					return ""
				}(),
				"error": errorString(execErr),
				"outputPreview": func() string {
					if execResult == nil {
						return ""
					}
					return truncateManagedCodexContinuationText(execResult.Output, 400)
				}(),
			},
		},
		sessionEventSummary: "Managed Codex worker resumed after governed tool execution.",
		progressSummary:     "Managed Codex worker is resuming after governed tool execution.",
		progressStage:       "resuming_after_tool_action",
		progressPercent:     85,
		commandText:         commandText,
		commandCWD:          cwd,
		timeoutSeconds:      timeoutSeconds,
		executionResult:     execResult,
		executionError:      errorString(execErr),
	})
}

func (s *APIServer) continueManagedWorkerAfterGovernedAction(ctx context.Context, session *SessionRecord, proposal *sessionToolProposal, action *ToolActionRecord, run *RunRecord, runErr error, decidedAt time.Time) bool {
	_ = decidedAt
	prepared, err := s.prepareManagedWorkerResumeContext(ctx, session, proposal, action)
	if err != nil {
		return false
	}
	return s.continueManagedWorkerWithPlan(ctx, session, proposal, action, prepared, managedWorkerResumePlan{
		requestPayloadFields: map[string]interface{}{
			"governedAction": map[string]interface{}{
				"status": action.Status,
				"runId": func() string {
					if run != nil {
						return run.RunID
					}
					return ""
				}(),
				"runStatus": func() string {
					if run != nil {
						return string(run.Status)
					}
					return ""
				}(),
				"policyDecision": func() string {
					if run != nil {
						return run.PolicyDecision
					}
					return ""
				}(),
				"selectedPolicyProvider": func() string {
					if run != nil {
						return run.SelectedPolicyProvider
					}
					return ""
				}(),
				"error": errorString(runErr),
			},
		},
		sessionEventSummary: "Managed Codex worker resumed after governed action evaluation.",
		progressSummary:     "Managed Codex worker is resuming after governed action evaluation.",
		progressStage:       "resuming_after_governed_action",
		progressPercent:     85,
		executionError:      errorString(runErr),
		governedRun:         run,
		failureRawResponse:  mustMarshalJSON(buildGovernedActionRunSnapshot(run)),
	})
}

func (s *APIServer) transitionSessionAfterStandaloneToolAction(ctx context.Context, session *SessionRecord, finalStatus ToolActionStatus, changedAt time.Time, proposal *sessionToolProposal, toolActionID string) {
	if s == nil || s.store == nil || session == nil || isTerminalSessionStatus(session.Status) {
		return
	}
	nextStatus := SessionStatusReady
	if finalStatus == ToolActionStatusFailed {
		nextStatus = SessionStatusReady
	}
	previousStatus := session.Status
	if previousStatus == nextStatus {
		return
	}
	session.Status = nextStatus
	session.CompletedAt = nil
	session.UpdatedAt = changedAt
	_ = s.store.UpsertSession(ctx, session)
	if task := loadTaskOrNil(ctx, s.store, session.TaskID); task != nil {
		task.LatestSessionID = session.SessionID
		task.Status = TaskStatusInProgress
		task.UpdatedAt = changedAt
		_ = s.store.UpsertTask(ctx, task)
	}
	s.appendSessionEventBestEffort(ctx, &SessionEventRecord{
		SessionID: session.SessionID,
		EventType: SessionEventType("session.status.changed"),
		Payload: mustMarshalJSON(map[string]interface{}{
			"previousStatus": previousStatus,
			"status":         session.Status,
			"proposalId":     normalizeStringOrDefault(proposal.ProposalID, ""),
			"toolActionId":   toolActionID,
		}),
		Timestamp: changedAt,
	})
}

func readStringFromJSONRaw(raw json.RawMessage, key string) string {
	return normalizedInterfaceString(parseRawJSONObject(raw)[key])
}

func readRawResponseFromJSONRaw(raw json.RawMessage) json.RawMessage {
	value := parseRawJSONObject(raw)["rawResponse"]
	switch typed := value.(type) {
	case json.RawMessage:
		return typed
	case []byte:
		return json.RawMessage(typed)
	case string:
		return json.RawMessage(typed)
	case nil:
		return nil
	default:
		return mustMarshalJSON(typed)
	}
}

func isSessionAwaitingToolProposalReview(ctx context.Context, store RunStore, sessionID string) bool {
	if store == nil || strings.TrimSpace(sessionID) == "" {
		return false
	}
	events, err := store.ListSessionEvents(ctx, SessionEventListQuery{
		SessionID: sessionID,
		Limit:     1000,
	})
	if err != nil {
		return false
	}
	proposals := map[string]bool{}
	for _, event := range events {
		payload := parseSessionEventPayloadObject(event.Payload)
		switch event.EventType {
		case SessionEventType("tool_proposal.generated"):
			proposalID := normalizedInterfaceString(payload["proposalId"])
			if proposalID != "" {
				proposals[proposalID] = true
			}
		case SessionEventType("tool_proposal.decided"):
			proposalID := normalizedInterfaceString(payload["proposalId"])
			if proposalID != "" {
				delete(proposals, proposalID)
			}
		}
	}
	return len(proposals) > 0
}

func loadTaskOrNil(ctx context.Context, store RunStore, taskID string) *TaskRecord {
	if store == nil || strings.TrimSpace(taskID) == "" {
		return nil
	}
	task, err := store.GetTask(ctx, taskID)
	if err != nil && err != sql.ErrNoRows {
		return nil
	}
	return task
}
