import test from "node:test";
import assert from "node:assert/strict";
import {
  buildNativeSessionActivitySummary,
  createOperatorChatThread,
  deriveOperatorChatThreadState,
  listNativeToolProposals,
  normalizeOperatorChatDraft
} from "../runtime/session-client.js";
import { loadM19ParityFixture, buildSessionViewFromParityFixture, buildChatThreadFromParityFixture } from "./m19-parity-fixture.js";

test("session client does not prefill legacy canned thread intent text", () => {
  const blankDraft = normalizeOperatorChatDraft({ executionMode: "managed_codex_worker" }, "codex");
  const legacyDraft = normalizeOperatorChatDraft(
    {
      executionMode: "managed_codex_worker",
      intent: "Run an operator-guided governed agent conversation through the M16 session contract."
    },
    "codex"
  );

  assert.equal(blankDraft.intent, "");
  assert.equal(legacyDraft.intent, "");
});

test("session client synthesizes a fresh thread intent when the field is blank", async () => {
  let capturedPayload = null;
  const api = {
    async createRuntimeTask(payload) {
      capturedPayload = payload;
      return {
        taskId: "task-123",
        title: payload.title,
        intent: payload.intent,
        createdAt: "2026-03-11T12:00:00Z"
      };
    }
  };

  const thread = await createOperatorChatThread(
    api,
    { tenantId: "12345", projectId: "12345" },
    { executionMode: "managed_codex_worker", agentProfileId: "codex", title: "", intent: "" }
  );

  assert.equal(capturedPayload.title, "Operator thread: codex");
  assert.equal(capturedPayload.intent, "Start a new governed Codex conversation for 12345.");
  assert.equal(capturedPayload.annotations?.threadIntent?.source, "autogenerated");
  assert.equal(capturedPayload.annotations?.threadIntent?.autogenerated, true);
  assert.equal(thread.intent, "Start a new governed Codex conversation for 12345.");
});

test("chat session client matches the shared M19 parity fixture", async () => {
  const fixture = await loadM19ParityFixture();
  const sessionView = buildSessionViewFromParityFixture(fixture);
  const activity = buildNativeSessionActivitySummary(sessionView);
  const proposals = listNativeToolProposals(sessionView);
  const threadState = deriveOperatorChatThreadState(buildChatThreadFromParityFixture(fixture));

  assert.equal(activity.latestWorkerSummary, fixture.expected.summary);
  assert.deepEqual(
    activity.progressItems.slice(-fixture.expected.eventLines.length).map((item) => `${item.label}: ${item.detail}`),
    fixture.expected.eventLines
  );
  assert.deepEqual(proposals.map((item) => item.proposalId), fixture.expected.proposalIds);
  assert.equal(activity.openApprovalCount, fixture.expected.approvalIds.length);
  assert.equal(threadState.uiStatus, "warn");
  assert.equal(threadState.openApprovalCount, fixture.expected.approvalIds.length);
  assert.match(threadState.message, /waiting/i);
});

test("session client preserves governed action proposal richness and linked run output", () => {
  const sessionView = {
    timeline: {
      session: { sessionId: "session-governed-1" },
      toolActions: [
        {
          toolActionId: "tool-action-governed-1",
          toolType: "governed_action_request",
          status: "COMPLETED",
          requestPayload: {
            proposalId: "proposal-governed-1"
          },
          resultPayload: {
            governedRun: {
              runId: "run-governed-1",
              status: "COMPLETED",
              policyDecision: "DEFER",
              selectedPolicyProvider: "aimxs-full",
              policyResponse: {
                decision: "DEFER"
              }
            }
          }
        }
      ],
      events: [
        {
          eventId: "event-generated-governed-1",
          sessionId: "session-governed-1",
          sequence: 10,
          eventType: "tool_proposal.generated",
          timestamp: "2026-03-10T13:00:00Z",
          payload: {
            proposalId: "proposal-governed-1",
            proposalType: "governed_action_request",
            workerId: "worker-governed-1",
            summary: "Managed Codex proposed a governed paper-trade request.",
            payload: {
              type: "governed_action_request",
              summary: "BUY 25 AAPL in paper account paper-main",
              requestLabel: "Paper Trade Request: AAPL",
              requestSummary: "BUY 25 AAPL in paper account paper-main",
              demoProfile: "finance_paper_trade",
              actionType: "trade.execute",
              resourceKind: "broker-order",
              resourceName: "paper-order-aapl",
              boundaryClass: "external_actuator",
              riskTier: "high",
              requiredGrants: ["grant.trading.supervisor"],
              evidenceReadiness: "PARTIAL",
              operatorApprovalRequired: false,
              handshakeRequired: true,
              financeOrder: {
                symbol: "AAPL",
                side: "buy",
                quantity: 25,
                account: "paper-main"
              }
            }
          }
        },
        {
          eventId: "event-decided-governed-1",
          sessionId: "session-governed-1",
          sequence: 14,
          eventType: "tool_proposal.decided",
          timestamp: "2026-03-10T13:01:00Z",
          payload: {
            proposalId: "proposal-governed-1",
            proposalType: "governed_action_request",
            workerId: "worker-governed-1",
            decision: "AUTO",
            status: "DEFERRED",
            reason: "Supervisor trading grant is still required.",
            toolActionId: "tool-action-governed-1",
            actionStatus: "COMPLETED",
            runId: "run-governed-1",
            runStatus: "COMPLETED",
            policyDecision: "DEFER",
            selectedPolicyProvider: "aimxs-full",
            operatorApprovalRequired: false
          }
        }
      ]
    },
    streamItems: []
  };

  const [proposal] = listNativeToolProposals(sessionView);
  assert.equal(proposal.proposalType, "governed_action_request");
  assert.equal(proposal.requestLabel, "Paper Trade Request: AAPL");
  assert.equal(proposal.requestSummary, "BUY 25 AAPL in paper account paper-main");
  assert.deepEqual(proposal.requiredGrants, ["grant.trading.supervisor"]);
  assert.equal(proposal.runId, "run-governed-1");
  assert.equal(proposal.policyDecision, "DEFER");
  assert.equal(proposal.selectedPolicyProvider, "aimxs-full");
  assert.equal(proposal.governedRun.runId, "run-governed-1");
  assert.equal(proposal.decision, "AUTO");
  assert.equal(proposal.status, "DEFERRED");
  assert.equal(proposal.operatorApprovalRequired, false);
});
