apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-runtime
spec:
  template:
    spec:
      containers:
        - name: runtime
          image: ghcr.io/epydios/epydios-agent-operations-plane-runtime@sha256:57a02ca7a2dfdbe09b2574e87864764fec91c9e27745840ad387f07ca433e4f9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-provider-registry-controller
spec:
  template:
    spec:
      containers:
        - name: controller
          image: ghcr.io/epydios/epydios-agent-operations-plane-extension-provider-registry-controller@sha256:a952d53141c932d6b8b18c5f17165126cf95b513a14e3648b48110c3478cd2f9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-profile-static-resolver
spec:
  template:
    spec:
      containers:
        - name: profile-resolver
          image: ghcr.io/epydios/epydios-agent-operations-plane-oss-profile-static-resolver@sha256:a11325971b027a90d2e72e4ad7c1aa99f6869734baf1ce37bcffa8486cfed61a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epydios-oss-policy-provider
spec:
  template:
    spec:
      containers:
        - name: policy-provider
          image: ghcr.io/epydios/epydios-agent-operations-plane-oss-policy-opa-provider@sha256:21418c580e115ffed134060946cfccf2f430d5aad970416e036a0396ec088d84
        - name: opa
          image: openpolicyagent/opa@sha256:15151b408ff6477e5f6b675e491cab60776be84be4fcbc19ca2d2024cec789bf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epydios-oss-evidence-provider
spec:
  template:
    spec:
      containers:
        - name: evidence-provider
          image: ghcr.io/epydios/epydios-agent-operations-plane-oss-evidence-memory-provider@sha256:1e3047021d317e2f5606413e2a0b956a80f36fa09dafcd82a2fe0ec1e8d6551d
